development:
  service: http://localhost:5000
  cas_server: https://localhost
  account_server: http://localhost:3000
production:
  service: http://admin.jurnalo.com
  cas_server: https://login.jurnalo.com
  account_server: http://accounts.jurnalo.com