development:
  service: http://localhost:3000
  cas_server: https://192.168.0.2/
  account_server: http://localhost:4000
production:
  service: http://admin.jurnalo.com
  cas_server: https://login.jurnalo.com
  account_server: http://accounts.jurnalo.com