ram:
  adapter: sqlite3
  database: /Users/ram/Workspace/jurnalo/JTier1-to-API/db/development.sqlite3

development:
  adapter: mysql
  encoding: utf8
  database: tier2_db_dev
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: tier2_db_prod
  username: jurnalo
  password: jp4t2db
  host: 10.176.228.50
  reconnect: true
